# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam-apiserver
  name: iam-apiserver
  namespace: tyk
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iam-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iam-apiserver
    spec:
      containers:
      - env:
        - name: TET
          value: test
        image: marmotedu/iam-apiserver-amd64:v0.0.3.dirty 
        imagePullPolicy: IfNotPresent
        name: iam-apiserver
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: iam
          mountPath: /root/.iam/iam-apiserver.yaml
          subPath: iam-apiserver.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: iam
        configMap:
          name: iam
          defaultMode: 420
          items:
          - key: iam-apiserver.yaml
            path: iam-apiserver.yaml
