# IAM应用节点列表（来源IP）
hosts:
  - 10.0.4.20
  - 10.0.4.21
# 来源IP可以访问的应用端口列表（iam-apiserver, iam-authz-server, iam-pump对外暴露的的端口）
ports:
  - 38080
  - 38443
  - 39090
  - 39443
  - 37070
# 来源IP可以访问的数据库端口列表（Redis, MariaDB, MongoDB）
dbports:
  - 33306
  - 36379
  - 57017
