apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-apiserver
  name: iam-apiserver
spec:
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: rpc
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: iam-apiserver
  sessionAffinity: None
  type: ClusterIP
