name: IamCI

on: 
  push:
    branchs:
    - '*'
  pull_request:
    types: [opened, reopened]

jobs:

  iamci:
    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: iamci

    strategy:
      matrix:
        go_version: [1.16]
        os: [ubuntu-latest]

    steps:

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go modules Tidy
        run: |
          echo 1

      - name: Generate all necessary files, such as error code files
        run: |
          echo 1

      - name: Check syntax and styling of go sources
        run: |
          echo 1

      - name: Run unit test and get test coverage
        run: |
          echo 1

      - name: Build source code for host platform
        run: |
          echo 1

      - name: Collect Test Coverage File
        run: |
          echo 1

      - name: Set up Docker Buildx
        run: |
          echo 1

      - name: Login to DockerHub
        run: |
          echo 1

      - name: Build docker images for host arch and push images to registry
        run: |
          echo 1
